# Generated by Django 3.0.3 on 2020-03-21 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_user_artist_id'),
        ('album', '0004_auto_20200320_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('Time_stamp', models.DateTimeField(auto_now_add=True)),
                ('Album', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
                ('User', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
