# Generated by Django 3.0.3 on 2020-03-10 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Music_key_type', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('Lright_type', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('Artist_note', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('Tags', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('Genre', models.CharField(max_length=80)),
                ('Time_stamp', models.DateTimeField(auto_now_add=True)),
                ('Album_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
            ],
        ),
    ]
