# Generated by Django 3.0.3 on 2020-03-21 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20200320_2356'),
        ('tag', '0002_remove_tag_track_id'),
        ('track', '0002_auto_20200320_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='Album_ID',
            new_name='Album',
        ),
        migrations.AddField(
            model_name='track',
            name='Playlist',
            field=models.ManyToManyField(blank=True, to='playlist.Playlist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='Tag',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tag.Tag'),
        ),
    ]
