# Generated by Django 3.0.4 on 2020-04-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20200320_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='Name',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
