# Generated by Django 3.0.4 on 2020-04-07 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_artist'),
        ('track', '0004_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='Artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
