# Generated by Django 3.0.3 on 2020-03-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordLabel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordlabel',
            name='Time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
