# Generated by Django 3.0.3 on 2020-03-10 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('tag', '0001_initial'),
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Playlist_image', models.URLField(blank=True, max_length=128, unique=True)),
                ('Name', models.CharField(max_length=80)),
                ('Description', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('Play_count', models.SmallIntegerField(default=0)),
                ('Time_stamp', models.DateTimeField(auto_now_add=True)),
                ('Album_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
                ('Tag_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag')),
                ('Track_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.track')),
            ],
        ),
    ]
