# Generated by Django 3.0.4 on 2020-04-15 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Playlist_image', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Name', models.CharField(max_length=80)),
                ('Description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Play_count', models.IntegerField(default=0)),
                ('Time_stamp', models.DateTimeField(auto_now_add=True)),
                ('User', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
