# Generated by Django 3.0.3 on 2020-03-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20200320_2141'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='Album_ID',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='Tag_ID',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='Description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='Play_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='Playlist_image',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='Track_ID',
        ),
        migrations.AddField(
            model_name='playlist',
            name='Track_ID',
            field=models.ManyToManyField(blank=True, to='track.track'),
        ),
    ]
