# Generated by Django 3.0.3 on 2020-03-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20200320_2356'),
        ('musicplayersetting', '0003_auto_20200321_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicplayersetting',
            name='Track',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Track'),
        ),
    ]
