# Generated by Django 3.0.4 on 2020-04-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_track_name'),
        ('musicplayersetting', '0004_auto_20200321_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicplayersetting',
            name='Track',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Track'),
        ),
    ]
