# Generated by Django 3.0.5 on 2020-04-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recordLabel', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_stamp', models.DateTimeField(auto_now_add=True)),
                ('Event', models.ManyToManyField(blank=True, to='event.Event')),
                ('RecordLabel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recordLabel.RecordLabel')),
            ],
        ),
    ]
