# Generated by Django 3.0.3 on 2020-03-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='User_ID',
        ),
    ]
