# Generated by Django 3.0.3 on 2020-03-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_artist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Event_ID',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='RecordLabel_ID',
            new_name='RecordLabel',
        ),
        migrations.AlterField(
            model_name='artist',
            name='Time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
