# Generated by Django 3.0.3 on 2020-03-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_artist'),
        ('artist', '0003_auto_20200320_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='User',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
