export const GET_TRACKS = "GET_TRACKS";
export const DELETE_TRACK = "DELETE_TRACK";
export const ADD_TRACK = "ADD_TRACK";


export const GET_ALBUMS = "GET_ALBUMS";
export const DELETE_ALBUMS = "DELETE_ALBUMS";
export const ADD_ALBUMS = "ADD_ALBUMS";
export const GET_ALBUMS_PASTMONTH = "GET_ALBUMS_PASTMONTH";

export const GET_USER = "GET_USER";
export const GET_SEARCH = "GET_SEARCH";
export const GET_USERTOTALPLAYCOUNT = "GET_USERTOTALPLAYCOUNT"
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_ERRORS = 'GET_ERRORS'; 