# Generated by Django 3.0.3 on 2020-03-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200319_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Artist_trigger',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='Followers',
            field=models.SmallIntegerField(default=0),
        ),
    ]
