# Generated by Django 3.0.3 on 2020-03-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20200320_2141'),
        ('user', '0004_auto_20200319_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Artist_trigger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='Bio',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='user',
            name='Playlist_ID',
        ),
        migrations.AddField(
            model_name='user',
            name='Playlist_ID',
            field=models.ManyToManyField(blank=True, to='playlist.Playlist'),
        ),
    ]
