# Generated by Django 3.0.3 on 2020-03-21 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_artist_user_id'),
        ('user', '0005_auto_20200320_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Artist_ID',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.Artist'),
        ),
    ]
