# Generated by Django 3.0.3 on 2020-03-21 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayersetting', '0001_initial'),
        ('user', '0006_user_artist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Artist_ID',
            new_name='Artist',
        ),
        migrations.AddField(
            model_name='user',
            name='Music_player',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicplayersetting.MusicPlayerSetting'),
        ),
    ]
