# Generated by Django 3.0.3 on 2020-03-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200320_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Playlist_ID',
        ),
    ]
