# Generated by Django 3.0.4 on 2020-04-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Name', models.CharField(max_length=80)),
                ('Cover_image', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Count', models.IntegerField(default=0)),
                ('Time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
