# Generated by Django 3.0.3 on 2020-03-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('Name', models.CharField(max_length=80)),
                ('Cover_image', models.URLField(blank=True, max_length=128, unique=True)),
                ('Count', models.SmallIntegerField(default=0)),
                ('Text', models.CharField(max_length=250)),
                ('Time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
