# Generated by Django 3.0.3 on 2020-03-21 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200319_2108'),
        ('album', '0002_album_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='Text',
        ),
        migrations.AlterField(
            model_name='album',
            name='Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='Cover_image',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='Description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='User_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
