# Generated by Django 3.0.4 on 2020-04-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Cover_image',
            field=models.FileField(default=None, null=True, upload_to='album_images'),
        ),
    ]
