# Generated by Django 3.0.3 on 2020-03-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20200320_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='User_ID',
            new_name='User',
        ),
    ]
