# Generated by Django 3.0.3 on 2020-03-10 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('Mood', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('Instruments', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('Time_stamp', models.DateTimeField(auto_now_add=True)),
                ('Track_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.track')),
            ],
        ),
    ]
